### ISSUE TITLE
trait/environmental figures not significant 

### ISSUE THREAD

**Issue by emilykelman** [caitlintwhite/KelmanProject#10]
I've been playing around with the CWM script to assess potential relationships between traits and environmental variables after Caitlin helped me to add all transects in area 7 (excluding 7_8) to the CWM data frame yesterday. I added a few figures to the figures folder and have been testing certain relationships based on other studies that I have read. I'm not having much luck finding any significant relationships. All of the p values I've calculated are around .4 and a lot of the adjusted r^2 values are negative.

**Comment by caitlintwhite** [comment]
Well done, Emily! No significance is still a result.. I looked at the figures you made and will think on it for a day or so. In the meantime could you also remake the stacked panel plot (showing spei_5 on the bottom, with SLA, and some of the other traits you used in the trait vs. environmental variable figures [can take out precip_5 at the top])? I'm interested in seeing trait response on all of the area 7 transects (minus 7_8) over time and am curious about trait responses and relative flucuation after certain drought years in the 2000s + post-2013. You can add more years displayed on your x-axis using the following line in your ggplot chunk:

scale_x_continuous(breaks = seq(1992, 2016, by = 2)) 

If the year labels bleed into each other, you can adjust them so they're easier to read using this line at the end of your ggplot chunk, just above the facet_grid line:
  
theme(axis.text.x = element_text(angle=45, hjust = 1))

The scale_x_continuous part adds major tick lines on the x-axis along a sequence of 1992 to 2016 in 2-year intervals; the theme line angles the x axis text at 45 degrees and horizontally moves the x axis text a tiny bit so it's better aligned with the tick marks.

**Comment by emilykelman** [comment]
Thanks, Caitlin. I'm trying to remake that panel plot but spei_5 isn't showing up on the plot even though it's included in CWM_merged_L and the code seems to be running just fine. Other than that, the traits that I tested yesterday are all visible on the plot. Any tips as to why spei_5 isn't showing up on the figure?

**Comment by julieelarson** [comment]
Hey Emily,

So, you are faceting by the trait_name column, right?? So any traits/climate variables you want to show up as separate panels have to be in that trait_names column. But if you look at the dataframe as it is, spei_5 is its own column still! so when you tell ggplot to include spei_5 from the trait_names column, it doesn't see it.

Lets go back to the line of code where you created this dataframe

#long form for creating figures 
CWM_climate_merged_L <- left_join(bos_cwm, clim_dat[c("year", "precip_12", "spei_12", "tmean_12", "spei_5")],  by=c("Year"="year"))%>%
  gather( key = "trait_name", value, RMR:seed_mass, precip_12, spei_12, tmean_12)

You see how when you gathered, you included all the traits, plus spei_12, precip_12, and tmean_12?  Try adding spei_5 into this code too, so that ends up being gathered into your trait_name column. Then when you rerun your ggplot code, it should work.

**Comment by caitlintwhite** [comment]
the other thing you could do to make your life easier whenever you modify traits used and/or climate variables you're merging is rearrange the bos_cwm columns so that sitekey, transect_ID and Year are the first three columns in the bos_cwm data frame. In doing this, the traits columns will always start in column 4, the climate variables will join to the right of the trait columns, and so when you use the gather function, you gather from column 4 to the very last column of the data frame [in R speak, 4:ncol(CWM_climate_merged_L)]. This would be the writing code more generically, which is always nice. 

If you're interested in that, I'd probably stick the line to rearrange columns in at the end of the section of code that makes the bos_cwm object (e.g. after rownames are re-named as a numeric sequence). You could use the dplyr::select() function to do this, or manually index the data frame, and use the traits vector, which will match all the column names for traits in the CWM data frame (since the CWM was made using the traits vector):

bos_cwm <- bos_cwm[c("sitekey", "transect_ID, "Year", traits)]

.. and then go on to all the code below "Explore CWM with other datasets"

**Comment by emilykelman** [comment]
Thank you guys! I uploaded the updated figure by just adding spei_5 to CWM_climate_merged_L. I'm also getting started trying to figure out how to calculate functional diversity. Should I start a new script for that?
