### ISSUE TITLE
Bad data entry for transect 7_7 in 2004, adjust input cover data

### ISSUE THREAD

**Issue by caitlintwhite** [caitlintwhite/KelmanProject#11]
BOSMP is looking in to this, but I found out today it looks like cover data was entered incorrectly for transect 7_7 in 2004, at least for some species. I haven't had time to look into this for the trait data, but if any of these species codes are in the lookup table, for now I would remove them from your input cover data frame for 7_7 in 2004:

[1] "acevul"               "agaten"               "alyaly-alydes-alypar" "anitec"              
 [5] "aripur"               "artfri"               "artlud"               "boucur"              
 [9] "brirosc"              "brojap"               "cammic"               "chelep"              
[13] "ciroch-cirund"        "dalcano"              "dalpur"               "echvir"              
[17] "erocic"               "evonut"               "gaumol"               "grisqu"              
[21] "hescom"               "hetfol"               "hetvil"               "lesmon"              
[25] "liapun"               "olipac"               "onomolo"              "orolud"              
[29] "pancap"               "psoten"               "vertha"   

I'll let you know when it's been resolved. I imagine BOSMP will resend a cleaned up dataset.

**Comment by caitlintwhite** [comment]
Okay, we have a resolution!

It looks like 7_2 and 7_7 abundance data were swapped in 2004. @emilykelman , in your code, you will need to switch the transect value and transect_ID value in 2004. Do you feel comfortable coding this, or do you want Julie or I to help?

**Comment by julieelarson** [comment]
Hey Emily,

I know it's frustrating when data corrections come up like this in the middle of analyses... another example of why such thorough data checking (QA/QC) and exploration are important upfront. (Remember also when we spent half an hour trying to make sure the trait data were right???)

Because these weren't our data, originally, it was harder for us to spot this, and a bummer. But luckily with R code laid out, it's mostly just a matter of fixing the original community data file and then re-running all the code.

This WILL mean that you will need to recreate the dataframes/CSV files for both the CWM and CWV values before proceeding, since both depend on the plant community data.  It's as easy as just running through all the code again in the right order, but you'll want to make extra sure that you have everything updated that feeds into your final figures and analyses. 

Hope this all makes sense.

With respect to actually coding out this swapping, I know it's actually a tricky problem, since you want to swap 7_2 and 7_7, but only for 2004.  I'm not exactly sure how to do this, myself (my default would have been to just go into the CSV file and correct the raw data, if they have true errors), but I'm sure we can get there via code. Let us know if you need help.

**Comment by emilykelman** [comment]
Hey guys,
So to switch the abundance data for 7_2 and 7_7, should I go into the tgsna_monitoring_clean raw dataset and switch the values manually? 

I'm not sure I know how to do that in the code. When I try to run the code in the explore_bos_cwm_climate script, it won't read in the bos_dat csv because the file has been removed.

**Comment by caitlintwhite** [comment]
Hang tight for 30min or so. I'm cleaning up some things on the repository, which is why your code is not working. I've already corrected the abundance data, so nothing for you to do there. 

And for future reference, never make a correction like that manually in the dataset .csv if it's not your own raw data :] When working with other pplz data, it's always good to document any changes you made to it in the code so others can replicate.

**Comment by caitlintwhite** [comment]
This is now corrected. @emilykelman, you'll see when you load the bos dataset, the column name for transect_ID is now "transect_ID.clean" (that's how you know you're using the corrected transects).

If your code uses "transect_ID" (e.g. in a plot or in an lm), you will either need to:
1) change the name of the column "transect_ID.clean" to "transect_ID" at the top of your code so everything below runs, OR
2)  do a search and replace in your code so that everything that is "transect_ID" is replaced with "transect_ID.clean".

I prefer option 2 because it's very clear what you're working with (especially when a correction was made halfway through your data analysis, like in our case). I've already done this for a few of your scripts (the script that generates the CWM tables and the script that analyzes CWM and CWV) and tested them to make sure they run.

Since this is fixed now, closing issue.
