### ISSUE TITLE
trying to graph 7_1 cover by merging bos_cwm and grpd cover

### ISSUE THREAD

**Issue by emilykelman** [caitlintwhite/KelmanProject#9]
I'm trying to create a figure for 7_1 cover over time and to do so I was going to use the bos_cwm dataframe which includes the traits, sitekey, transect_ID (with only 7_1), and year.  I'm trying to merge that dataframe with grouped cover so that I can graph relative cover of 7_1 over time. I'm having trouble generating grouped cover because when I run the code it says object "Transect" is not found. I don't want to change it because I know the code worked before! I think I will be able to explain my issue better in person tomorrow, but just wanted to give you guys a heads up.

**Comment by caitlintwhite** [comment]
If the ggplot code wants "Transect" but the variable name in the data frame is "transect_ID", feel free to edit the ggplot code to call on "transect_ID". OR, the issue could be, there is a line creating transect_ID from the variables "Area" and "Transect" and that line isn't needed anymore because "transect_ID" is already in the data frame you're using. If so, just comment out that line.

Regardless, we can look at it later today
